---
title: "Group_14 KEras"
author: "DenizN"
date: "03/11/2019"
output: html_document
---



```{r}
source("SC000_Initialisation.R")
source("SC001_Data_Preparation.R")

library(keras)
library(caret)
library(mltools)

ecstacy_CL <- c("ecstacy")

data <- data.frame(drug_consumption)[c(psych_variables,demographic_variables,usage_variables_nested_all)]

inTrain <- createDataPartition(data$"neuroticism", p = .80, list = FALSE)
x_train <- as.matrix(data[inTrain, c(psych_variables,demographic_variables)])
x_test <- as.matrix(data[-inTrain, c(psych_variables,demographic_variables)])
y_train <- as.matrix(data[inTrain, usage_variables_nested_all])
y_test <- as.matrix(data[-inTrain, usage_variables_nested_all])

```



```{r}
model <- keras_model_sequential() 

model %>% 
  layer_dense(units = 256, activation = 'relu', input_shape = dim(x_train)[2]) %>% 
  layer_dropout(rate = 0.2) %>% 
  layer_dense(units = 128, activation = 'relu') %>% 
  layer_dropout(rate = 0.2) %>% 
  layer_dense(units = 32, activation = 'relu') %>% 
  layer_dropout(rate = 0.2) %>% 
  layer_dense(units = 16, activation = 'relu') %>%
  
  layer_dropout(rate = 0.2) %>%
  layer_dense(units = dim(y_train)[2], activation = 'softmax')

```

```{r}
model %>% compile(
  loss = 'binary_crossentropy',
  optimizer = optimizer_rmsprop(),
  metrics = c('accuracy')
)
```

```{r}
model
```

```{r}
history <- model %>% fit(
  x_train, y_train, 
  epochs = 100, batch_size = 32, 
  validation_split = 0.2
)
```


```{r}
model %>% predict_classes(x_test)
```


