---
title: "Group_14 KEras"
author: "DenizN"
date: "03/11/2019"
output: html_document
---

```{r}
library(keras)
library(caret)
library(mltools)

ecstacy_CL <- c("ecstacy_CL0","ecstacy_CL1","ecstacy_CL2","ecstacy_CL3","ecstacy_CL4","ecstacy_CL5","ecstacy_CL6")

data <- data.frame(drug_consumption)[c(psych_variables,demographic_variables,ecstacy_CL)]

inTrain <- createDataPartition(data$neuroticism, p = .60, list = FALSE)
train_x <- data[inTrain, c(psych_variables,demographic_variables)]
test_x <- data[-inTrain, c(psych_variables,demographic_variables)]
train_y <- as.factor(data[inTrain, ecstacy_CL])
test_y <- as.factor(data[-inTrain, ecstacy_CL])



```

```{r}
test_y
```


```{r}
model <- keras_model_sequential() 

model %>% 
  layer_dense(units = 256, activation = 'relu', input_shape = dim(train_x)[2]) %>% 
  layer_dropout(rate = 0.4) %>% 
  layer_dense(units = 128, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = dim(train_y)[2], activation = 'softmax')

```

```{r}
model %>% compile(
  loss = 'categorical_crossentropy',
  optimizer = optimizer_rmsprop(),
  metrics = c('accuracy')
)
```

```{r}
dim(train_y)
```

```{r}
model
```


```{r}
history <- model %>% fit(
  train_x, train_y, 
  epochs = 10, batch_size = 1, 
  validation_split = 0.2
)
```


```{r}
model %>% predict_classes(x_test)
```


